// =============================================================================
// app.config.js — dynamic wrapper around app.base.json.
//
// Every value in app.base.json is the PROD identity: package `com.epurse.app`,
// plain "ePurse" name/icon — that one must never change, since Play Store
// listing, OAuth clients, and Play App Signing are all bound to it.
//
// build.sh (local `-test` targets) and eas.json (every `-prod`/EAS profile)
// both already export EXPO_PUBLIC_APP_VARIANT + EXPO_PUBLIC_BUILD_KIND before
// prebuild runs — see build.sh's own header comment for the two-axis meaning.
// This file reads those same two vars to work out which of the 4 non-prod
// build variants (dev-test, dev-prod, stage-test, stage-prod) is being built,
// and if so swaps in a variant-suffixed package name + app name + badged
// launcher icon (assets/variants/, generated by
// scripts/make-icon-badges.py) — so all 5 targets can be installed side by
// side on one device/emulator without one overwriting another, and so the
// launcher icon alone tells you which build you're looking at.
//
// A bare `production`/unset APP_VARIANT (the real `prod` target) resolves to
// VARIANT_KEY = null and every override below is skipped — app.base.json's
// own values pass through untouched.
// =============================================================================
const base = require('./app.base.json');

const APP_VARIANT = process.env.EXPO_PUBLIC_APP_VARIANT; // undefined | 'development' | 'stage' | 'production'
const BUILD_KIND = process.env.EXPO_PUBLIC_BUILD_KIND;   // undefined | 'test' | 'prod'

function resolveVariantKey() {
  if (APP_VARIANT === 'development') return BUILD_KIND === 'test' ? 'dtest' : 'dprod';
  if (APP_VARIANT === 'stage') return BUILD_KIND === 'test' ? 'stest' : 'sprod';
  return null;
}

const VARIANT_KEY = resolveVariantKey();

const VARIANT_LABELS = { dtest: 'D-Test', dprod: 'D-Prod', stest: 'S-Test', sprod: 'S-Prod' };

// No app.json exists any more, so the `config` the function form normally
// receives is just Expo's package.json-derived defaults (e.g. name: "epurse",
// lowercase, from this repo's package.json) — NOT something to merge over
// app.base.json. app.base.json alone is authoritative; `config` is ignored.
module.exports = () => {
  if (!VARIANT_KEY) return { expo: base.expo };

  const label = VARIANT_LABELS[VARIANT_KEY];
  return {
    expo: {
      ...base.expo,
      name: `ePurse ${label}`,
      icon: `./assets/variants/icon-${VARIANT_KEY}.png`,
      android: {
        ...base.expo.android,
        package: `${base.expo.android.package}.${VARIANT_KEY}`,
        adaptiveIcon: {
          ...base.expo.android.adaptiveIcon,
          foregroundImage: `./assets/variants/adaptive-icon-${VARIANT_KEY}.png`,
        },
      },
    },
  };
};
